---INNER JOIN--
--JOINING ELECTION AND CROP YEILD 

SELECT * FROM ELECTION
SELECT * FROM CROP
SELECT ID,STATE,ACTION_TAKEN FROM ELECTIONS AS E
SELECT ID,STATE,AREA,CROP_YEAR FROM CROP AS C

SELECT E.ID,E.STATE,E.ACTION_TAKEN,C.STATE,C.AREA,C.CROP_YEAR FROM ELECTION AS E
INNER JOIN CROP AS C
ON E.STATE=C.STATE

--LEFT JOIN
-- OUTPUT SAME AS INNER JOIN

SELECT * FROM ELECTION
SELECT * FROM CROP
SELECT ID,STATE,ACTION_TAKEN FROM ELECTIONS AS E
SELECT ID,STATE,AREA,CROP_YEAR FROM CROP AS C

SELECT E.ID,E.STATE,E.ACTION_TAKEN,C.STATE,C.AREA,C.CROP_YEAR FROM ELECTION AS E
LEFT JOIN CROP AS C
ON E.ID=C.ID

--RIGHT JOIN
-- GETTING ALL THE COLUMNS BUT SHOW NULL VALUES AT LEFT SIDE BECAUSE TABLE OF ELECTION
-- DOESN'T HAVE MUCH DATA
	
SELECT E.ID,E.STATE,E.ACTION_TAKEN,C.STATE,C.AREA,C.CROP_YEAR FROM ELECTION AS E
RIGHT JOIN CROP AS C
ON E.ID=C.ID

--FULL JOIN 
--COMBINES ALL THE DATA
-- GET SAME OUTPUT AS SAME AS RIGHT JOIN

SELECT E.ID,E.STATE,E.ACTION_TAKEN,C.STATE,C.AREA,C.CROP_YEAR FROM ELECTION AS E
FULL JOIN CROP AS C
ON E.ID=C.ID


-- extra using where,limit,offset
SELECT E.ID,E.STATE,E.ACTION_TAKEN,C.STATE,C.AREA,C.CROP_YEAR FROM ELECTION AS E
FULL JOIN CROP AS C
ON E.ID=C.ID
WHERE e.STATE='West Bengal'
limit 5
offset 5



